import {detectBrowserAICapabilities} from '../runtime/models/browser-capabilities.mjs';
import {STARTER_MODELS,getStarterModel} from '../runtime/models/model-manifest.mjs';
import {createBrowserTransformersHost} from '../runtime/models/browser-transformers-host.mjs';
import {createBrowserTransformersCognitiveModel} from '../runtime/models/browser-cognitive-model.mjs';

const $=id=>document.getElementById(id); let host=null,model=null,requestCounter=0;
const state={capabilities:null,loadMs:null,ttftMs:null,elapsedMs:null,tokensPerSecond:null,cache:'unknown / not asserted',failure:null};
function metric(label,value){return `<div class="metric"><b>${label}</b><span>${value??'—'}</span></div>`}
function renderMetrics(){const m=host?.provenance?.()||{};$('metrics').innerHTML=[metric('model',m.modelId||'not loaded'),metric('revision',m.revision||'—'),metric('backend',m.device||$('backend').value),metric('dtype',m.dtype||'—'),metric('runtime',m.runtime||'@huggingface/transformers@4.3.0'),metric('inference','browser-local / no remote API'),metric('load elapsed',state.loadMs==null?'—':`${state.loadMs} ms`),metric('TTFT',state.ttftMs==null?'—':`${state.ttftMs} ms`),metric('generation',state.elapsedMs==null?'—':`${state.elapsedMs} ms`),metric('tokens/sec',state.tokensPerSecond??'not available'),metric('cache',state.cache),metric('failure',state.failure||'none')].join('')}
function selected(){return getStarterModel($('model').value)}
function disclose(){const m=selected(),device=$('backend').value,mb=m?.approximatePrimaryWeightMB?.[device];$('disclosure').textContent=m?`${m.model} · ${device==='webgpu'?m.webgpuDtype:m.wasmDtype} · approximately ${mb??'unknown'} MB primary weights. Nothing downloads until Load model is pressed.`:'';renderMetrics()}
function progress(event){const n=Number(event?.progress);if(Number.isFinite(n))$('progress').value=Math.max(0,Math.min(100,n));$('status').textContent=`Loading locally: ${event?.file||event?.status||'model assets'}${Number.isFinite(n)?` · ${n.toFixed(0)}%`:''}`}
async function capabilities(){state.capabilities=await detectBrowserAICapabilities();const c=state.capabilities;$('capabilities').innerHTML=[metric('WebGPU',c.webgpu.available?`available${c.webgpu.fp16?' · shader-f16':''}`:'unavailable'),metric('WASM',c.wasm?'available':'unavailable'),metric('workers',c.workers?'available':'unavailable'),metric('device memory hint',c.deviceMemoryGB==null?'not exposed':`${c.deviceMemoryGB} GB (advisory)`),metric('logical CPUs',c.hardwareConcurrency??'not exposed'),metric('CacheStorage',c.cacheStorage?'available':'unavailable')].join('');if(!c.webgpu.available){$('backend').value='wasm';$('status').textContent='WebGPU unavailable; WASM selected. Loading remains user-controlled.'}disclose()}
async function estimateStorage(){try{const e=await navigator.storage?.estimate?.();if(e&&Number.isFinite(e.usage)&&Number.isFinite(e.quota))state.cache=`storage API: ${(e.usage/1048576).toFixed(1)} MB used / ${(e.quota/1048576).toFixed(0)} MB quota; model cache hit not asserted`;}catch{}renderMetrics()}
function setBusy(b){$('load').disabled=b;$('generate').disabled=b||(!model&&$('runtime').value!=='mock');$('stop').disabled=!b||!model}
async function load(){if($('runtime').value==='mock'){$('status').textContent='Deterministic/mock control selected. No neural model downloaded.';$('generate').disabled=false;return}state.failure=null;$('progress').value=0;setBusy(true);const manifest=selected(),device=$('backend').value;if(device==='webgpu'&&!state.capabilities?.webgpu?.available){state.failure='WebGPU selected but unavailable; choose WASM explicitly.';$('status').textContent=state.failure;setBusy(false);renderMetrics();return}host=createBrowserTransformersHost({manifest,device,dtype:device==='webgpu'?manifest.webgpuDtype:manifest.wasmDtype,onProgress:progress});model=createBrowserTransformersCognitiveModel({host,onText:t=>$('log').textContent+=t});try{const t=await model.load();state.loadMs=t.loadElapsedMs;$('progress').value=100;$('status').textContent='Model ready. Conversation will route through the typed CognitiveModel boundary.';await estimateStorage()}catch(e){state.failure=String(e?.message||e);$('status').textContent=state.failure;host=null;model=null}finally{setBusy(false);renderMetrics()}}
async function generate(){if($('runtime').value==='mock'){$('log').textContent='[mock control] deterministic model path selected; no neural generation performed on this page.';return}if(!model)return;$('log').textContent='';setBusy(true);$('stop').disabled=false;const prompt=$('prompt').value;const artifactId=`local-user-${++requestCounter}`;const input={requestId:`local-request-${requestCounter}`,requestingModule:'ObserverScientist',inferenceType:'engineering-conversation',contextManifest:[{artifactId,epistemicStatus:'observation',content:{userText:prompt}}],causalSourceIds:[artifactId],maxResponseUnits:96,expectedEpistemicStatus:'inference',hiddenContextPolicy:'none'};try{const r=await model.infer(input);state.ttftMs=r.timing.ttftMs;state.elapsedMs=r.timing.elapsedMs;$('status').textContent=r.status==='cancelled'?'Generation cancelled; model remains loaded.':r.status==='ok'?'Generation complete locally through CognitiveModel.':`Local inference failed: ${r.failure}`;$('provenance').textContent=JSON.stringify({requestId:r.requestId,provider:r.provider,causalSourceIds:r.causalSourceIds,accessibleArtifactIds:r.content?.accessibleArtifactIds||[],epistemicStatus:r.epistemicStatus},null,2)}catch(e){state.failure=String(e?.message||e);$('status').textContent=state.failure}finally{setBusy(false);renderMetrics()}}
$('model').innerHTML=STARTER_MODELS.map(m=>`<option value="${m.id}">${m.label}</option>`).join('');
$('model').addEventListener('change',disclose);$('backend').addEventListener('change',()=>{host=null;model=null;$('generate').disabled=true;disclose()});$('runtime').addEventListener('change',()=>{const mock=$('runtime').value==='mock';$('load').disabled=mock;$('generate').disabled=!mock&&!model;$('status').textContent=mock?'Mock control selected — no model download required.':'Local neural mode selected — press Load model explicitly.'});$('load').addEventListener('click',load);$('generate').addEventListener('click',generate);$('stop').addEventListener('click',()=>model?.cancel());
renderMetrics();await capabilities();await estimateStorage();