import {decodeEnvelope,displayCode,pairingPayloadFromHash} from './swarm-protocol.mjs';
import {CONNECTION_MODES,QrSwarmPeer} from './swarm-peer.mjs';
import {DEFAULT_STUN_URL} from './swarm-network.mjs';
import {renderQr,QR_MODULE_URL} from './qr.mjs';

const $=id=>document.getElementById(id);const pairChannel=new BroadcastChannel('conscios-swarm-pairing-v2');let activePeer=null;let pendingOffer=null;
function show(id,visible=true){$(id).classList.toggle('hidden',!visible)}
function setStatus(message,tone=''){$('globalStatus').textContent=message;$('globalStatus').className=`status ${tone}`}
function pretty(value){try{return JSON.stringify(value,null,2)}catch{return String(value)}}
function hostNickname(){return $('nickname').value.trim()||'Phone'}function guestNickname(){return $('joinNickname').value.trim()||'Phone'}
function selectedMode(){return $('connectionMode').value}
function networkInput(){const mode=selectedMode();return {connectionMode:mode,stunUrls:$('stunUrls').value.trim()||DEFAULT_STUN_URL,turnCredentialEndpoint:CONNECTION_MODES[mode].requiresTurn?$('turnCredentialEndpoint').value.trim()||null:null}}
function updateModeUi(){const mode=selectedMode();const meta=CONNECTION_MODES[mode];$('modeDescription').textContent=meta.description;show('internetFields',mode!=='local');show('turnFields',meta.requiresTurn)}
function updateProvenance(extra={}){$('provenance').textContent=pretty({protocol:'conscios-swarm/v2',transport:'WebRTC DataChannel + AES-256-GCM application layer',signaling:'QR/link URL fragment only',connectionMode:activePeer?.connectionMode??selectedMode(),iceTransportPolicy:activePeer?.networkConfig?.iceTransportPolicy??null,iceServerCount:activePeer?.networkConfig?.iceServers?.length??null,credentialExpiresAt:activePeer?.credentialExpiresAt??null,qrRenderer:QR_MODULE_URL,role:activePeer?.role??null,sessionId:activePeer?.sessionId??null,safetyCode:activePeer?.safetyCode??null,safetyConfirmed:activePeer?.safetyConfirmed??false,remoteVerified:activePeer?.remoteVerified??false,transportInfo:activePeer?.transportInfo??null,exoEndpoint:activePeer?.exoEndpoint??null,remoteNickname:activePeer?.remoteNickname??null,remoteCapabilities:activePeer?.remoteCapabilities??null,lastRttMs:activePeer?.lastRttMs??null,...extra})}
async function copyText(text){await navigator.clipboard.writeText(text);setStatus('Copied pairing link.','ok')}
function networkLabel(mode){return CONNECTION_MODES[mode]?.label??mode}

function bindPeer(peer){
  activePeer=peer;
  peer.addEventListener('state',event=>{const state=event.detail.connectionState||event.detail.iceConnectionState||'connecting';$('connectionPill').textContent=state;if(state==='connected'){show('connectedCard');setStatus(peer.connectionMode==='local'?'Direct local peer connection established.':'Internet peer transport established. Verify the safety code.','ok')}updateProvenance({connectionState:state})});
  peer.addEventListener('safety-code',event=>{$('safetyCode').textContent=event.detail.safetyCode;if(event.detail.requiresConfirmation){show('safetyCard');$('safetyHint').textContent='Do not share compute or metadata until both people confirm this exact code.'}else{show('safetyCard',false)}updateProvenance()});
  peer.addEventListener('verification',event=>{const remote=event.detail.remote;const local=event.detail.local;$('verificationState').textContent=local?(remote?'Verified end-to-end · both peers confirmed':'Your safety code is confirmed · waiting for peer confirmation'):'Safety verification pending';$('verificationState').className=`status ${local?(remote?'ok':'warn'):''}`;if(local)show('safetyCard',false);updateProvenance()});
  peer.addEventListener('transport',event=>{$('transportState').textContent=`ICE path: local ${event.detail.localCandidateType||'?'} → remote ${event.detail.remoteCandidateType||'?'} · ${event.detail.protocol||'unknown protocol'}`;updateProvenance()});
  peer.addEventListener('peer',event=>{$('peerName').textContent=event.detail.nickname||'Peer';$('peerCapability').textContent=pretty(event.detail.capabilities);$('connectedExo').textContent=event.detail.exoEndpoint||peer.exoEndpoint||'No exo endpoint shared.';show('connectedCard');updateProvenance()});
  peer.addEventListener('exo-endpoint',event=>{$('connectedExo').textContent=event.detail.exoEndpoint||'No exo endpoint shared.';updateProvenance()});peer.addEventListener('rtt',event=>{$('rtt').textContent=`Encrypted round-trip: ${event.detail.rttMs.toFixed(1)} ms`;updateProvenance()});peer.addEventListener('channel-close',()=>setStatus('Peer data channel closed.','warn'));peer.addEventListener('error',event=>setStatus(event.detail.message||'Peer error.','bad'));
}

async function createHost(){
  cleanupPeer();const network=networkInput();if(CONNECTION_MODES[network.connectionMode].requiresTurn&&!network.turnCredentialEndpoint)throw new Error('Reliable/private internet mode requires a TURN credential endpoint.');
  const peer=new QrSwarmPeer({role:'host',nickname:hostNickname()});bindPeer(peer);setStatus(`Creating ${networkLabel(network.connectionMode)} WebRTC offer…`,'warn');
  const result=await peer.createOffer({exoEndpoint:$('exoEndpoint').value.trim()||null,...network});$('offerLink').value=result.url;$('offerCode').textContent=displayCode(peer.sessionId);show('inviteCard');show('joinCard',false);show('answerCard',false);$('hostStatus').textContent='Invite ready. Waiting for the guest answer.';
  const qrMeta=await renderQr($('offerQr'),result.url,{cellSize:3,margin:12});updateProvenance({pairing:'host-offer-ready',qrCharacters:qrMeta.characters,qrModules:qrMeta.moduleCount});setStatus('Invite ready. Scan nearby or send the link remotely.','ok');
}
async function loadOffer(encoded){
  const offer=await decodeEnvelope(encoded);if(offer.kind!=='offer')throw new Error('Expected a swarm offer.');pendingOffer={encoded,offer};$('joinHost').textContent=offer.nickname||'Host';$('joinCode').textContent=displayCode(offer.sessionId);$('joinMode').textContent=networkLabel(offer.connectionMode);$('joinTurn').textContent=offer.turnCredentialEndpoint||'none';$('joinExo').textContent=offer.exoEndpoint||'none';$('joinExpires').textContent=new Date(offer.expiresAt).toLocaleTimeString();
  show('modeCard',false);show('inviteCard',false);show('joinCard');show('answerCard',false);updateProvenance({pairing:'offer-loaded',sessionId:offer.sessionId,offerHost:offer.nickname,connectionMode:offer.connectionMode,turnCredentialEndpoint:offer.turnCredentialEndpoint,exoEndpoint:offer.exoEndpoint});setStatus('Invitation loaded. Review network/relay details, then tap Join.','warn');
}
async function joinOffer(){
  if(!pendingOffer)throw new Error('No invitation loaded.');cleanupPeer();const peer=new QrSwarmPeer({role:'guest',nickname:guestNickname()});bindPeer(peer);$('joinStatus').textContent='Creating encrypted WebRTC answer…';const result=await peer.acceptOffer(pendingOffer.encoded);$('answerLink').value=result.url;show('answerCard');$('joinStatus').textContent='Answer ready. Return it to the host.';
  const qrMeta=await renderQr($('answerQr'),result.url,{cellSize:3,margin:12});updateProvenance({pairing:'guest-answer-ready',qrCharacters:qrMeta.characters,qrModules:qrMeta.moduleCount});setStatus('Answer ready. Scan it nearby or send the link back remotely.','ok');
}
async function applyAnswer(encoded,{source='manual'}={}){
  const answer=await decodeEnvelope(encoded);if(answer.kind!=='answer')throw new Error('Expected a swarm answer.');if(!activePeer||activePeer.role!=='host'||activePeer.sessionId!==answer.sessionId){localStorage.setItem(`conscios-swarm-answer-v2:${answer.sessionId}`,encoded);pairChannel.postMessage({type:'answer',sessionId:answer.sessionId,encoded});show('modeCard',false);show('inviteCard',false);show('joinCard',false);show('answerCard',false);$('globalStatus').textContent='Answer delivered to the original host tab if it is open. You may close this tab.';updateProvenance({pairing:'answer-relay',sessionId:answer.sessionId,source});return}
  await activePeer.acceptAnswer(encoded);$('hostStatus').textContent='Answer accepted. Establishing encrypted peer link…';setStatus('Answer accepted. Connecting…','ok');updateProvenance({pairing:'answer-applied',source});
}
function cleanupPeer(){if(activePeer){activePeer.close();activePeer=null}show('connectedCard',false);show('safetyCard',false)}
function reset(){cleanupPeer();pendingOffer=null;history.replaceState(null,'',location.pathname+location.search);show('modeCard');show('inviteCard',false);show('joinCard',false);show('answerCard',false);setStatus('Ready.');updateProvenance()}
async function applyLink(text){const value=String(text||'').trim();if(!value)throw new Error('Paste a pairing link first.');const url=new URL(value,location.href);const payload=pairingPayloadFromHash(url.hash);if(!payload)throw new Error('This is not a ConsciOS swarm pairing link.');if(payload.kind==='offer')await loadOffer(payload.encoded);else await applyAnswer(payload.encoded,{source:'pasted-link'})}

pairChannel.addEventListener('message',event=>{const msg=event.data;if(msg?.type!=='answer'||!activePeer||activePeer.role!=='host'||msg.sessionId!==activePeer.sessionId)return;applyAnswer(msg.encoded,{source:'broadcast-channel'}).catch(error=>setStatus(error.message,'bad'))});
window.addEventListener('storage',event=>{if(!activePeer||activePeer.role!=='host'||event.key!==`conscios-swarm-answer-v2:${activePeer.sessionId}`||!event.newValue)return;applyAnswer(event.newValue,{source:'storage-event'}).catch(error=>setStatus(error.message,'bad'))});
$('connectionMode').addEventListener('change',updateModeUi);$('createButton').addEventListener('click',()=>createHost().catch(error=>setStatus(error.message,'bad')));$('joinButton').addEventListener('click',()=>joinOffer().catch(error=>setStatus(error.message,'bad')));$('confirmSafety').addEventListener('click',()=>{try{activePeer?.confirmSafetyCode();setStatus('Safety code confirmed locally. Waiting for peer confirmation if needed.','ok')}catch(error){setStatus(error.message,'bad')}});$('applyManual').addEventListener('click',()=>applyLink($('manualPayload').value).catch(error=>setStatus(error.message,'bad')));$('copyOffer').addEventListener('click',()=>copyText($('offerLink').value).catch(error=>setStatus(error.message,'bad')));$('copyAnswer').addEventListener('click',()=>copyText($('answerLink').value).catch(error=>setStatus(error.message,'bad')));$('cancelHost').addEventListener('click',reset);$('leaveButton').addEventListener('click',reset);$('pingButton').addEventListener('click',()=>activePeer?.ping().then(()=>$('rtt').textContent='Encrypted ping sent…').catch(error=>setStatus(error.message,'bad')));$('openWorkbench').addEventListener('click',()=>{const endpoint=activePeer?.exoEndpoint;if(endpoint)localStorage.setItem('conscios-exo-endpoint',endpoint);location.href='../workbench/'});
updateModeUi();const initial=pairingPayloadFromHash();if(initial?.kind==='offer')loadOffer(initial.encoded).catch(error=>setStatus(error.message,'bad'));else if(initial?.kind==='answer')applyAnswer(initial.encoded,{source:'scanned-answer'}).catch(error=>setStatus(error.message,'bad'));else updateProvenance();
